[package]
name = "svv-ergebnis-anzeige"
version = "0.1.0"
authors = ["Korbinian Maier <korbinian.maier@tum.de>"]
edition = "2018"

[dependencies]
iron = "0.6.0"
# rpi-led-matrix = "0.1.1"

failure = "0.1.3"
bytes = "0.4.10"